notifications:
  email:
    on_success: never
  slack:
    on_success: never
Sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
before_install:
  - gem install bundler --no-document -v 1.17.3
script: bundle exec rake test
