notifications:
  email: false
  slack:
    on_success: never
Sudo: false
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
before_install: gem install bundler
script: bundle exec rake test
