notifications:
  email: false
  slack:
    on_success: never
Sudo: false
language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
before_install: gem install bundler
script: bundle exec rake test
